### ISSUE TITLE
Issues with Colorusage and Readability

### ISSUE THREAD

**Issue by domsch1988** [jorgerojas26/lazysql#1]
So, i'm not sure on which end this issue is, but i'm not getting the same color output as your screenshots do
![grafik](https://github.com/jorgerojas26/lazysql/assets/1961154/713c45f9-7741-42d6-b790-b0a5ddd319d5)

Especially the unfocused treeview is using a Blue no matter which colorscheme i use. This is in Windows Terminal, tested with 3 colorschemes.

Additionally i feel like the contrast on the selected cell is pretty low. A darker foreground color for that would help readability.

**Comment by jorgerojas26** [comment]
Hello, thanks for the issue.

I did not test in Windows, but definitely there is a problem with colors there. I will be investigating this issue, thanks for pointing out.

**Comment by sabovyan** [comment]
I am not sure but as far as I have noticed lazysql doesn't use the background color of the terminal, but instead uses default color which in my case was color1.  and I had to tweak a little bit to have solid background color. 
![colro1](https://github.com/jorgerojas26/lazysql/assets/58337011/b50f107a-77f8-43b8-9c9c-4e970db1022c)

**Comment by andradei** [comment]
Same kind of issue on linux when using a light theme in the terminal.

**Comment by jorgerojas26** [comment]
> Same kind of issue on linux when using a light theme in the terminal.

Yes, there are problems with the theme right now, colors are hardcoded. I can take a look at this, but feel free to open a PR if you know how to resolve this problem easily.

**Comment by jorgerojas26** [comment]
@andradei @sabovyan @domsch1988 can you check if #70 fix the problem?

**Comment by andradei** [comment]
@jorgerojas26 I'll check when the AUR updates the version. Thank you for working on this.

**Comment by prochac** [comment]
Same here. The selected schema says `partman`, as you "can" see.
![image](https://github.com/user-attachments/assets/5d62242b-ecba-4b06-9332-c1d64e1c01de)

I'm using KDE Konsole with default Breeze color scheme

**Comment by prochac** [comment]
> @jorgerojas26 I'll check when the AUR updates the version. Thank you for working on this.

you can update on your own
```
yay --editmenu -S lazysql
```
and edit these lines in the PKGBUILD
```
pkgver=0.2.7
sha256sums=('08066f0e094c7fcf62841daa66e96f226d6b459db343e5e0cb4d9b5ed30bd3f9')
```

**Comment by prochac** [comment]
Unfortunately, my problem last.

This is selected "partman" schema.
![image](https://github.com/user-attachments/assets/e9afe1a5-f70f-490b-968d-bca2a748ae47)

Here it's the "queues_test" database what's selected.
![image](https://github.com/user-attachments/assets/9d771df6-9fb2-410e-b2ad-e9c115362e1e)

For selected table, I finally have a slight clue what's being selected.
![image](https://github.com/user-attachments/assets/75d4575c-31ed-491e-825b-1417a382ea49)

**Comment by jorgerojas26** [comment]
@prochac Can you please check if #99 fixes the issue?

**Comment by prochac** [comment]
@jorgerojas26 now it works for me :) all text is white, and the selected has orange background :+1: 

![Screencast_20240904_190630](https://github.com/user-attachments/assets/1ecbbd4a-12ef-4d33-8c1d-bd16ea7e0b1a)
