### ISSUE TITLE
Windows: Unable to access SQLITE Database

### ISSUE THREAD

**Issue by JustBarnt** [jorgerojas26/lazysql#101]
# Reproduction

## Operating System Information
```
OS: Windows 11 Pro
Build: 10.0.22632
Terminal: Wezterm -V wezterm 20240812-215703-30345b36
Go Version: go1.23.0 windows/amd64
```
## Installed via go
`go install github.com/jorgerojas26/lazysql@latest`

## Steps
1. Install `lazysql` via `go`
2. Create a temporary sqlite database (I was just trying to access my hours.db base from the 'hours' time tracking TUI)
3. Run `lazysql`
4. You will be presented with this screen, which compared to what I see when running it in WSL or my Ubuntu distro the URL field is missing and completely unknown until I hit tab. 
![image](https://github.com/user-attachments/assets/67034fed-bff8-4c16-a9a2-4fbe0c096d3d)
5. After entering `name` and `url`
6. I tried to connect I was given the following error `unable to open database file: out of memory (14)`
a. I also tried 'C:/users/bwilliams/hours.db` as the url since that is the absolute path to the `hours.db` file and was given the error of `unknown database scheme`. 

I did some digging and I found the `config.toml` file located in `~/.config/lazysql` I opened that and edited it to the following

```toml
[[database]]
Name = 'Hours'
Provider = 'sqlite3'
DBName = 'hours'
URL = 'C:/users/bwilliams/hours.db'
```

After editing the `config.toml` file I could run `lazysql` and then access the sqlite db as expected.

It seems to potentially be an issue of it not accepting a windows path that includes the a drive letter, as well as potentially the DBName field not being a field that's available to fill out?

Note: I tried changing URL back to `~/hours.db` and leaving the DBName field filled out and it gave the original error `unable to open database file: out of memory (14)` again. So it seems to need an absolute path?

**Comment by andersonsilva87** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by jorgerojas26** [comment]
Hi.

I think the URL field is missing just because of the size of the screen. Can you make a separate issue with that so i can address it there?

For the sqlite path, i'll test a bit more in Windows to see what's happening there. But for now, you can try with the format: `file:path` to see if the problem persist even with the "file:" prefix.

**Comment by JustBarnt** [comment]
@jorgerojas26 Understood! I will give this a try! Thank you!

**Comment by JustBarnt** [comment]
Yes using `file:path` works.
I tried the following
1. `file:C:/users/bwilliams/hours.db` -> Works
2. `file:~/hours.db` -> Fails as expected cause that is not a valid UNC path with same error as above
3. `file:./hours.db` -> Works as a relative location to `lazysql.exe`

**Comment by jorgerojas26** [comment]
Phenomenal !

So, i think we can close this issue then and make a separate one with the UI?

**Comment by jorgerojas26** [comment]
By the way, the `file:path` format is on the README of the repo, i accept suggestions there if the doc is not very clear.

**Comment by JustBarnt** [comment]
@jorgerojas26 Correct we can close this indeed! 

And I don't think it is needed. It just now hit me that I was trying an URL for sqlite and not sqlite3 which is the provider I have windows... So that's on me. Thanks again!!
