### ISSUE TITLE
Cannnot connect to postgresql using special characters in password

### ISSUE THREAD

**Issue by eb-microlab-digital** [jorgerojas26/lazysql#109]
Cannot save / test / connect by using complex password containing special characters like ^, #, [, ] and/or $.

The error message is invalid port ":password^" after host.

These are the url's tested format:
- postgres://username:password@host:port/dbname
- pg://username:password@host:port/dbname?sslmode=disable

**Comment by jorgerojas26** [comment]
Passwords that contains special characters must be URL encoded.

**Comment by eb-microlab-digital** [comment]
Worked like a charm. 

Thank you for quick response!

PS: It will be great if the Readme.md will be enriched with additional note about this situation.
