### ISSUE TITLE
Creating a table does not reflect in the TUI

### ISSUE THREAD

**Issue by gytic** [jorgerojas26/lazysql#118]
When you use the `SQL Editor` to create a table, it does not reflect inside the TUI and you have to restart lazysql to see the changes.

# Reproduction

> This was tested with SQLite

1. open `lazysql`
2. connect to a database
3. open SQL Editor and execute `CREATE TABLE` query
    - `CREATE TABLE test (id integer PRIMARY KEY);`
 4. switch back to table list -> new table is not visible

# Expectation
It would be nice to 'refresh' the table list after a new table was created, and maybe even add a shortcut for manual refreshing of the table list.

Would it be possible to filter the query-string for 'CREATE' or 'create' and if either one of them is present refresh the table list after the query was executed?

**Comment by jorgerojas26** [comment]
Thanks for pointing out this. Maybe the manual refresh shortcut can solve this for now.

I'm planning to refactor the table Tree logic soon, the code is not that good.

Can you open a PR adding the shortcut "r" to refresh the tree?

**Comment by jorgerojas26** [comment]
> Yeah I can do that.
> 
> Should it be a _global_ hotkey or just when the tree is focused?

A tree hotkey, not global.
