### ISSUE TITLE
Is there a way to limit column width?

### ISSUE THREAD

**Issue by svanharmelen** [jorgerojas26/lazysql#125]
Just learned about this tool and as a big fan of LazyGit wanted to give it a try. So far it seems to work quite well!

But I have a few tables that have columns with (very) long strings in them. Currently such a column has the same width as the width of the table window itself. Is there a way to configure the min/max column width to prevent one column from being so wide if there are more columns to display (of course fine to fill up the space if there are no more columns to display).

Thanks!

**Comment by jorgerojas26** [comment]
Right now there is no way, that would definitely be a good improve.

**Comment by svanharmelen** [comment]
Check... I might take a stab at it, given enough time and motivation 😉
