### ISSUE TITLE
WSL Error missing X11

### ISSUE THREAD

**Issue by BadBossy** [jorgerojas26/lazysql#13]
```
❯ go install github.com/jorgerojas26/lazysql@latest
go: downloading github.com/jorgerojas26/lazysql v0.1.2
go: downloading golang.design/x/clipboard v0.7.0
go: downloading github.com/rivo/tview v0.0.0-20240101144852-b3bd1aa5e9f2
go: downloading github.com/google/uuid v1.5.0
go: downloading github.com/xo/dburl v0.20.2
go: downloading github.com/gdamore/tcell/v2 v2.7.0
go: downloading github.com/pelletier/go-toml/v2 v2.1.1
go: downloading github.com/lucasb-eyer/go-colorful v1.2.0
go: downloading golang.org/x/sys v0.15.0
go: downloading golang.org/x/term v0.15.0
go: downloading github.com/gdamore/encoding v1.0.0
go: downloading github.com/mattn/go-runewidth v0.0.15
go: downloading github.com/rivo/uniseg v0.4.3
# golang.design/x/clipboard
clipboard_linux.c:15:10: fatal error: X11/Xlib.h: No such file or directory
   15 | #include <X11/Xlib.h>
compilation terminated.
```

System executed the command:
Win11 with WSL2 Ubuntu 22.04.3 LTS

**Comment by jaymorelli96** [comment]
I am also having the same problem in the installation with WSL2 OpenSUSE Tumbleweed

**Comment by jaymorelli96** [comment]
Solution is to install the `libX11-dev` package. I guess in ubuntu is `sudo apt-get install -y libx11-dev`. In my case the issue was solved installing with my package manager `sudo zypper in libX11-devel`

**Comment by jorgerojas26** [comment]
> Solution is to install the `libX11-dev` package. I guess in ubuntu is `sudo apt-get install -y libx11-dev`. In my case the issue was solved installing with my package manager `sudo zypper in libX11-devel`

Awesome. I'll close the issue for now, feel free to reopen if the issue persist.
