### ISSUE TITLE
Only getting "endleui" screen

### ISSUE THREAD

**Issue by remino** [jorgerojas26/lazysql#143]
Hi,

I got the x86_64 binary to run on Ubuntu 20.04 (because good luck making `go install` work) and all I get is this screen:

![image](https://github.com/user-attachments/assets/ca33dca5-8350-4295-a0ec-961714ba9d55)

I can quit with `Q`, but that's pretty much all I can do. Am I missing something?

**Comment by jorgerojas26** [comment]
The UI of the connection selection screen have that problem as of now when the screen is small, but everything should work fine. Just press "n" to save a new connection, once saved it will be listed, you can press 'c' or 'Enter" to connect to it.

**Comment by remino** [comment]
That did work. Thank you. I can also just edit the `config.toml` file.

Although oddly enough when I point it to an SQLite file that doesn’t exist (e.g. typo in URL), it says there’s not enough memory. But I guess that’s another issue.
