### ISSUE TITLE
Need help connecting to postgres

### ISSUE THREAD

**Issue by bermell** [jorgerojas26/lazysql#2]
I usually connect to postgres database with `psql` like this: 
```shell
psql postgresql://postgres:mysecretpassword@localhost:5432/postgres
```

Using `lazysql` I can't manage to create a connection though. I get two kinds of error messages when pressing F2 to test the connection.  

If I set URL: 
postgresql://postgres:mysecretpassword@localhost:5432/postgres
I get error message:
sql: unknown driver "postgres" (forgotten import?)

If I set URL: 
localhost:5432/postgres
I get error message
unknown database scheme

Is it just that lazysql doesn't support postgres or am I doing something wrong?

Awesome that you're building lazysql, I use lazygit and lazydocker daily at work. Keep it up!! :)

**Comment by bermell** [comment]
Any clue as to how much work it would be to some basic postgres functionality? I been wanting a reason to try Go, if it's just about implementing an interface I might give it a go (pun intended!) at some point.

**Comment by jorgerojas26** [comment]
Hi, thanks for the issue.

I will be addressing this, there is some work to be done to support multiple databases.

You are right, an interface needs to be created along with logic to use the correct driver to connect to the database.

**Comment by parasit** [comment]
I have just started working on a "driver" for postgresql, but as you write, some changes to the code will be required so that it can use one common interface, regardless of the connected database.

The first versions should be ready soon :)

**Comment by jorgerojas26** [comment]
Awesome @parasit 

Indeed, some code need to be changed for that. Thank you very much mate for your time. This project will be awesome because the community is just amazing.

**Comment by jorgerojas26** [comment]
I just created a PR that implements Postgres support. Please check it out and give some feedback.

There are still some issues on the create,update,delete logic that i will address in another branch.

Also, there's still some work to be done in the Tree to support 3 levels of nodes for postgres catalog > schema > table hierarchy.
