### ISSUE TITLE
[feat]: support to icons

### ISSUE THREAD

**Issue by KevenGoncalves** [jorgerojas26/lazysql#20]
I'm big fan of TUI like lazygit and lazydocker, and rice terminals, would be nice if lazyqsl had support to icons like others TUIs mentioned here

**Comment by jorgerojas26** [comment]
Of course, that would be awesome. I'm also a big fan of ricing my terminal.

But for now, i'm focusing on functionality, supporting more RDBMS, refactor code, add more features, etc.

If someone wants to give it a shot with the icons, it will be very appreciated by everyone.

**Comment by KevenGoncalves** [comment]
I will give a try on this

**Comment by KevenGoncalves** [comment]
This is how its going
<img width="1440" alt="Captura de Tela 2024-01-21 às 03 48 43" src="https://github.com/jorgerojas26/lazysql/assets/80492657/c1b1fced-c88a-42b8-9d23-0933d9c079cd">
<img width="1440" alt="Captura de Tela 2024-01-21 às 03 49 10" src="https://github.com/jorgerojas26/lazysql/assets/80492657/7ccd272a-8d2b-4dbf-9f03-8e006dfff380">

**Comment by jorgerojas26** [comment]
Oh god, this is looking so good bro. Really good work.

**Comment by GusJelly** [comment]
I hope this isn't a dumb question but how did you integrate the program into neovim's ui? I've seen this before with lazygit but I never understood how it works. @KevenGoncalves

**Comment by KevenGoncalves** [comment]
> I hope this isn't a dumb question but how did you integrate the program into neovim's ui? I've seen this before with lazygit but I never understood how it works. @KevenGoncalves


Well I have not integrated directly in neovim like lazygit, what I have done is open a floating terminal and run the artifact , see toggleterm plugin

**Comment by KevenGoncalves** [comment]
This is the last version, now working in config to make optional for those who don't want icons

<img width="1440" alt="Captura de Tela 2024-01-21 às 09 51 06" src="https://github.com/jorgerojas26/lazysql/assets/80492657/ca0587a4-cb8b-44f7-bac5-2845747f07c7">

**Comment by jorgerojas26** [comment]
Awesome work, that looks nice...

**Comment by jorgerojas26** [comment]
Any progress in this?

**Comment by jorgerojas26** [comment]
@KevenGoncalves i'm going to close this for inactivity. Please reopen and come back with a PR if you want. I'm sure we would love that icons integration.
