### ISSUE TITLE
[bug]: application crash when try to open a table

### ISSUE THREAD

**Issue by KevenGoncalves** [jorgerojas26/lazysql#23]
I found this bug in the now, when I was working on the support of icons, when try to open a table it crash
<img width="1440" alt="Captura de Tela 2024-01-21 às 03 49 18" src="https://github.com/jorgerojas26/lazysql/assets/80492657/f0c70f14-e8a1-4f4b-a1da-97c5b3933977">

**Comment by jorgerojas26** [comment]
That is a reggresion, i'll fix that asap.
