### ISSUE TITLE
Can't Connect With Special Characters in Mysql Password

### ISSUE THREAD

**Issue by wstewarttennes** [jorgerojas26/lazysql#25]
Not able to connect with special characters or replacing special characters in the password field with their `%` representation.

**Comment by jorgerojas26** [comment]
I found a solution for this. It was just a matter of escaping the url string correctly. 

I will make a PR soon.

**Comment by pixelskull** [comment]
Not quite sure if it is related to this, when trying to connect to a postgres database I get the error that it could not parse the url: 

> pg://user:pass@localhost/db_name?sslmode=disable

`parse "pg://user:pass@localhost%2Fdb_name?sslmode=disable": invalid URL escape "%2F"` 

the %2F is obviously the escaped "/". It seems that encoding with the net/url package does not like the schema.

**Comment by jorgerojas26** [comment]
> Not quite sure if it is related to this, when trying to connect to a postgres database I get the error that it could not parse the url:
> 
> > pg://user:pass@localhost/db_name?sslmode=disable
> 
> `parse "pg://user:pass@localhost%2Fdb_name?sslmode=disable": invalid URL escape "%2F"`
> 
> the %2F is obviously the escaped "/". It seems that encoding with the net/url package does not like the schema.

The URL encoding/decoding is done internally, please try with the raw connection url string, without the escaped "/".

**Comment by pixelskull** [comment]
Oh sorry, the quote from the earlier post is my input. I entered it without escape, but after saving it seems to be escaped. 
Just to be clear, this is my input: pg://user:pass@localhost/db_name?sslmode=disable

**Comment by jorgerojas26** [comment]
Ok, the problem here is that it is not parsing correctly your input because of the /db_name, if i put the url without the "/db_name" it work correctly.

I'll work on that.

**Comment by pixelskull** [comment]
Thanks for your effort. I am stroked to use this awesome project :)

**Comment by jorgerojas26** [comment]
I'm thinking of reverting the changes i made to do the escaping internally, this adds a lot of unnecessary complexity that could be avoided if the users just escape their connection strings.

I'm working on it, so we can move on to develop other features.

**Comment by pixelskull** [comment]
Since the fix was working for passwords, you could slice the user and password section, and use the escaping only for this part. There shouldn't be a case for the url part to be escaped, since every occurrence of a special character here will break the url?!
