### ISSUE TITLE
What is valid database scheme？

### ISSUE THREAD

**Issue by hf-xz** [jorgerojas26/lazysql#28]
<img width="562" alt="image" src="https://github.com/jorgerojas26/lazysql/assets/27397614/002e460f-a7e3-4b4f-8a3a-bd7b7b908adf">

What should I put into the `URL` ??

I've tried:

```
jdbc:mysql://hostname:port/database
jdbc:mysql://hostname:port/database?user=username&password=userpassword
hostname:port
```

but none of them work, showing `unknown database scheme`.

**Comment by jorgerojas26** [comment]
The following are examples of database connection URLs:

`postgres://user:pass@localhost/dbname
pg://user:pass@localhost/dbname?sslmode=disable
mysql://user:pass@localhost/dbname
mysql:/var/run/mysqld/mysqld.sock
sqlserver://user:pass@remote-host.com/dbname
mssql://user:pass@remote-host.com/instance/dbname
ms://user:pass@remote-host.com:port/instance/dbname?keepAlive=10
oracle://user:pass@somehost.com/sid
sap://user:pass@localhost/dbname
sqlite:/path/to/file.db
file:myfile.sqlite3?loc=auto
odbc+postgres://user:pass@localhost:port/dbname?option1=`

**Comment by GusJelly** [comment]
@hf-xz If you want to learn more about how the app parses the url look into the library dburl for go. It should be a standard connection string that would work in other apps like DBeaver or Sql-Server Management studio.

**Comment by jorgerojas26** [comment]
i'll close this issue, please feel free to reopen if you have a problem connecting with a particular scheme.

**Comment by hf-xz** [comment]
Press `F2` I get:

<img width="495" alt="image" src="https://github.com/jorgerojas26/lazysql/assets/27397614/252536f3-05e6-4cd9-970d-fb482b92747f">

But when I try to save using `F1`, I get:

<img width="400" alt="image" src="https://github.com/jorgerojas26/lazysql/assets/27397614/eea4a070-0116-46ed-b44f-28e98fe7321a">

What's wrong with this?
