### ISSUE TITLE
Test success but can't save or connect.

### ISSUE THREAD

**Issue by hf-xz** [jorgerojas26/lazysql#30]
Press `F2` I get:

<img width="495" alt="image" src="https://github.com/jorgerojas26/lazysql/assets/27397614/252536f3-05e6-4cd9-970d-fb482b92747f">

But when I try to save using `F1`, I get:

<img width="400" alt="image" src="https://github.com/jorgerojas26/lazysql/assets/27397614/eea4a070-0116-46ed-b44f-28e98fe7321a">

What's wrong with this?

_Originally posted by @hf-xz in https://github.com/jorgerojas26/lazysql/issues/28#issuecomment-1920741532_

**Comment by jorgerojas26** [comment]
Please post your URL input here, so i can replicate.

**Comment by b3nb5n** [comment]
Im having this same issue with this postgres url `pg://postgres:@192.168.0.250/crud`
