### ISSUE TITLE
Connecting to a mysql database does not seem to work in main branch

### ISSUE THREAD

**Issue by DylanElens** [jorgerojas26/lazysql#34]
### Steps to reproduce
1. clone repo
2. go run main.go
3. New connection

My input for the url ``mysql://root:password@localhost:33061/database``

It prints out the following error when trying to test it:
```bash
dial tcp: lookup localhost:33061:33061: no such host  
```
and this error when pressing enter to connect to it
```bash
parse "mysql://root:password@localhost:33061%2Fdata": invalid port ":
```

I did some inspecting in the code and found that it ***probably*** has something to do with the ``EscapeConnectionString`` function in utils.go
The reason I came to that conclusion is that when replacing this:
```go
connectionString := helpers.EscapeConnectionString(form.GetFormItem(1).(*tview.InputField).GetText())
parsed, err := helpers.ParseConnectionString(connectionString)
```
with:

```go
parsed, err := helpers.ParseConnectionString(form.GetFormItem(1).(*tview.InputField).GetText())
```
It seemed to work for my end, however there will be no sanitization done. I don't know enough about the code to change this so I thought I would make just make the issue. Let me know if you need more information from my end.

**Comment by pixelskull** [comment]
It seems to be related to my comment on #25.
