### ISSUE TITLE
Cannot commit changes

### ISSUE THREAD

**Issue by slapcat** [jorgerojas26/lazysql#35]
**Issue Summary**
When I go to save a change, I get this error:

```
Unknown column 'id' in 'where clause'
```

**Steps to Reproduce**
1. Connect to database
2. View cell, press `c` to edit, modify text
3. Press `ctrl+s` to try and commit change

![image](https://github.com/jorgerojas26/lazysql/assets/52802566/41113e04-8465-47cb-92c6-e98682e3c3ce)

**Comment by jorgerojas26** [comment]
This is indeed a very bad problem with the way all the logic for DML statements is written, i'm working on a refactor where an `id` column is not needed to perform DML statements.
