### ISSUE TITLE
[idea] Go TUI framework (Bubbletea) that could help development

### ISSUE THREAD

**Issue by Rem0ld** [jorgerojas26/lazysql#37]
Hello,
I've seen your project from ChrisCool discord which looks promising. 
I love TUI app!
I also know this company is making amazing software for developing apps in Go.
https://github.com/charmbracelet
This is the framework to develop TUI app.
https://github.com/charmbracelet/bubbletea

And they also have other stuff to make forms, cli apps etc.. You should look into it.

**Comment by jorgerojas26** [comment]
Thanks for the suggestion, i'm closing this as for now.
