### ISSUE TITLE
No idea about what to put in new connection form

### ISSUE THREAD

**Issue by luisnquin** [jorgerojas26/lazysql#42]
I can't guess the required format of my connection values, maybe some placeholder or a (? - help) key and of course, documentation about it can help.

Here's how I wanted to create a connection to the MySQL database of my company
![image](https://github.com/jorgerojas26/lazysql/assets/86449787/47311bd1-5dab-4fae-ad97-7016540516ca)

**Comment by jorgerojas26** [comment]
I'll add that to the documentation, but for now, check this: https://github.com/xo/dburl?tab=readme-ov-file#example-urls
