### ISSUE TITLE
Windows binaries missing cgo

### ISSUE THREAD

**Issue by bennettscience** [jorgerojas26/lazysql#46]
The pre-compiled Windows builds did not include the  `CGO_ENABLED` flag and cannot open SQLite files.

![Snag_2abb6162](https://github.com/jorgerojas26/lazysql/assets/3878010/0824c1bd-bb7c-4248-b314-771b7707833a)

**Comment by cameronj86** [comment]
Experiencing the same issue on Debian (Bookworm)

![image](https://github.com/jorgerojas26/lazysql/assets/8635023/729ed6f0-fabb-44ef-85c9-bc8f39add814)

**Comment by ityc** [comment]
Experiencing the same issue on [Debian (buster)](https://www.debian.org/releases/buster/)
![image](https://github.com/jorgerojas26/lazysql/assets/1253963/5fe2d849-657f-4880-847e-e79c46ffc6d3)
