### ISSUE TITLE
Cannot open databases with all-numeric names

### ISSUE THREAD

**Issue by kc8rwr** [jorgerojas26/lazysql#47]
Using build 0.1.8 in Debian Bookworm under WLS2

I noticed this connected to two similarly configured MySQL servers.
I do not know if it is a MySQL specific problem or not.

I can see all the databases in the table panel.
I can open ones with letters in their names, even if they start with a number.
All-numeric databases do not open. I can select them but nothing happens when I press enter.

I hope this is helpful, thanks!

**Comment by jorgerojas26** [comment]
@kc8rwr Can you please check if #67 completely solves your issue?

**Comment by jorgerojas26** [comment]
And sorry for being late. I was very busy for a few months in my job.

**Comment by kc8rwr** [comment]
This seems to have fixed it. Thank you very much!
