### ISSUE TITLE
fatal error: X11/Xlib.h: No such file or directory

### ISSUE THREAD

**Issue by mkellyxp** [jorgerojas26/lazysql#48]
I'm on NixOS 23.11, using sway on wayland.  When trying to build this via Go, ran into this error.  I'm curious if this is due to being on wayland?

Steps to reproduce:

On NixOS, running the Sway wm.
1. Opened terminal (I am using foot)
2. nix-shell -p go
3. go install github.com/jorgerojas26/lazysql@latest

It will result in:

```
# golang.design/x/clipboard
clipboard_linux.c:15:10: fatal error: X11/Xlib.h: No such file or directory
   15 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```

![image](https://github.com/jorgerojas26/lazysql/assets/6528226/e79588ac-bf8a-45f2-8ce8-98d73e6f47f1)

**Comment by kanielrkirby** [comment]
Ah, unfortunate. I was going to build this package for Nix, but ran into this as well.

**Comment by LinPr** [comment]
This might works when I met this question on Ubuntu18.04 


Firstly, I execute this command , oops!  fail 
```
$ sudo apt-get install libx11-dev                                          

    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
    
    The following packages have unmet dependencies:
     libx11-dev : Depends: libx11-6 (= 2:1.6.4-3ubuntu0.4) but 2:1.6.4-3ubuntu0.5 is to be installed
                  Recommends: libx11-doc but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.
```

and accroding to the error message, then I execute 

```
$ sudo apt-get install libx11-6=2:1.6.4-3ubuntu0.4                                           

      Reading package lists... Done
      Building dependency tree
      Reading state information... Done
      The following packages will be DOWNGRADED:
        libx11-6
      0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 70 not upgraded.
      Need to get 572 kB of archives.
      After this operation, 0 B of additional disk space will be used.
      Do you want to continue? [Y/n] y
      Get:1 http://mirrors.aliyun.com/ubuntu bionic-security/main amd64 libx11-6 amd64 2:1.6.4-3ubuntu0.4 [572 kB]
      Fetched 572 kB in 0s (1,383 kB/s)
      dpkg: warning: downgrading libx11-6:amd64 from 2:1.6.4-3ubuntu0.5 to 2:1.6.4-3ubuntu0.4
      (Reading database ... 177547 files and directories currently installed.)
      Preparing to unpack .../libx11-6_2%3a1.6.4-3ubuntu0.4_amd64.deb ...
      Unpacking libx11-6:amd64 (2:1.6.4-3ubuntu0.4) over (2:1.6.4-3ubuntu0.5) ...
      Setting up libx11-6:amd64 (2:1.6.4-3ubuntu0.4) ...
      Processing triggers for libc-bin (2.27-3ubuntu1.5) ...

```

Then I execute the  first command  again,  it  works now  

`$  sudo apt-get install libx11-dev

      Reading package lists... Done
      Building dependency tree
      Reading state information... Done
      The following additional packages will be installed:
        libpthread-stubs0-dev libx11-doc libxau-dev libxcb1-dev libxdmcp-dev x11proto-core-dev x11proto-dev
        xorg-sgml-doctools xtrans-dev
      Suggested packages:
        libxcb-doc
      The following NEW packages will be installed:
        libpthread-stubs0-dev libx11-dev libx11-doc libxau-dev libxcb1-dev libxdmcp-dev x11proto-core-dev
        x11proto-dev xorg-sgml-doctools xtrans-dev
      0 upgraded, 10 newly installed, 0 to remove and 70 not upgraded.
      Need to get 3,162 kB of archives.
      After this operation, 15.7 MB of additional disk space will be used.
      Do you want to continue? [Y/n] y
      Get:1 http://mirrors.aliyun.com/ubuntu bionic/main amd64 libpthread-stubs0-dev amd64 0.3-4 [4,068 B]
      Get:2 http://mirrors.aliyun.com/ubuntu bionic/main amd64 xorg-sgml-doctools all 1:1.11-1 [12.9 kB]
      Get:3 http://mirrors.aliyun.com/ubuntu bionic/main amd64 x11proto-dev all 2018.4-4 [251 kB]
      Get:4 http://mirrors.aliyun.com/ubuntu bionic/main amd64 x11proto-core-dev all 2018.4-4 [2,620 B]
      Get:5 http://mirrors.aliyun.com/ubuntu bionic-updates/main amd64 libxau-dev amd64 1:1.0.8-1ubuntu1 [9,476 B]
      Get:6 http://mirrors.aliyun.com/ubuntu bionic/main amd64 libxdmcp-dev amd64 1:1.1.2-3 [25.1 kB]
      Get:7 http://mirrors.aliyun.com/ubuntu bionic/main amd64 xtrans-dev all 1.3.5-1 [70.5 kB]
      Get:8 http://mirrors.aliyun.com/ubuntu bionic-updates/main amd64 libxcb1-dev amd64 1.13-2~ubuntu18.04 [80.0 kB]
      Get:9 http://mirrors.aliyun.com/ubuntu bionic-security/main amd64 libx11-dev amd64 2:1.6.4-3ubuntu0.4 [641 kB]Get:10 http://mirrors.aliyun.com/ubuntu bionic-security/main amd64 libx11-doc all 2:1.6.4-3ubuntu0.4 [2,065 kB]
      Fetched 3,162 kB in 3s (1,098 kB/s)
      Selecting previously unselected package libpthread-stubs0-dev:amd64.
      (Reading database ... 177547 files and directories currently installed.)
      Preparing to unpack .../0-libpthread-stubs0-dev_0.3-4_amd64.deb ...
      Unpacking libpthread-stubs0-dev:amd64 (0.3-4) ...
      Selecting previously unselected package xorg-sgml-doctools.
      Preparing to unpack .../1-xorg-sgml-doctools_1%3a1.11-1_all.deb ...
      Unpacking xorg-sgml-doctools (1:1.11-1) ...
      Selecting previously unselected package x11proto-dev.
      Preparing to unpack .../2-x11proto-dev_2018.4-4_all.deb ...
      Unpacking x11proto-dev (2018.4-4) ...
      Selecting previously unselected package x11proto-core-dev.
      Preparing to unpack .../3-x11proto-core-dev_2018.4-4_all.deb ...
      Unpacking x11proto-core-dev (2018.4-4) ...
      Selecting previously unselected package libxau-dev:amd64.
      Preparing to unpack .../4-libxau-dev_1%3a1.0.8-1ubuntu1_amd64.deb ...
      Unpacking libxau-dev:amd64 (1:1.0.8-1ubuntu1) ...
      Selecting previously unselected package libxdmcp-dev:amd64.
      Preparing to unpack .../5-libxdmcp-dev_1%3a1.1.2-3_amd64.deb ...
      Unpacking libxdmcp-dev:amd64 (1:1.1.2-3) ...
      Selecting previously unselected package xtrans-dev.
      Preparing to unpack .../6-xtrans-dev_1.3.5-1_all.deb ...
      Unpacking xtrans-dev (1.3.5-1) ...
      Selecting previously unselected package libxcb1-dev:amd64.
      Preparing to unpack .../7-libxcb1-dev_1.13-2~ubuntu18.04_amd64.deb ...
      Unpacking libxcb1-dev:amd64 (1.13-2~ubuntu18.04) ...
      Selecting previously unselected package libx11-dev:amd64.
      Preparing to unpack .../8-libx11-dev_2%3a1.6.4-3ubuntu0.4_amd64.deb ...
      Unpacking libx11-dev:amd64 (2:1.6.4-3ubuntu0.4) ...
      Selecting previously unselected package libx11-doc.
      Preparing to unpack .../9-libx11-doc_2%3a1.6.4-3ubuntu0.4_all.deb ...
      Unpacking libx11-doc (2:1.6.4-3ubuntu0.4) ...
      Setting up libpthread-stubs0-dev:amd64 (0.3-4) ...
      Setting up xorg-sgml-doctools (1:1.11-1) ...
      Setting up x11proto-dev (2018.4-4) ...
      Setting up xtrans-dev (1.3.5-1) ...
      Setting up libxdmcp-dev:amd64 (1:1.1.2-3) ...
      Setting up libx11-doc (2:1.6.4-3ubuntu0.4) ...
      Setting up x11proto-core-dev (2018.4-4) ...
      Setting up libxau-dev:amd64 (1:1.0.8-1ubuntu1) ...
      Setting up libxcb1-dev:amd64 (1.13-2~ubuntu18.04) ...
      Setting up libx11-dev:amd64 (2:1.6.4-3ubuntu0.4) ...
      Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
`


Finally , run go install , everything works now 
`go install github.com/jorgerojas26/lazysql@latest`

**Comment by kanielrkirby** [comment]
@LinPr That helped, actually! Appreciate you sharing, I probably should have checked if there was a Nix package that matched what was missing.

I'll try to package this for Nix soon (but still gotta do a little research on how that process works, and it likely won't be added right away), but for now, if you just want something that works, add this binary to your `environment.systemPackages` or `home-manager.users.your-username.home.packages` list:

```nix
(buildGoModule rec {
  pname = "lazysql";
  version = "0.1.8";

  src = fetchFromGitHub {
    owner = "jorgerojas26";
    repo = "lazysql";
    rev = "v${version}";
    hash = "sha256-yPf9/SM4uET/I8FsDU1le9JgxELu0DR9k7mv8PnBwvQ=";
  };

  vendorHash = "sha256-tgD6qoCVC1ox15VPJWVvhe4yg3R81ktMuW2dsaU69rY=";

  buildInputs = [
    xorg.libX11
  ];
})
```

All I really did was look for the `libX11` package, and add it into the `buildInputs` list. You *might* have to change the hash, version, etc., but it *should* work.

@mkellyxp Hope this helps! If it does, don't forget to close the issue.

**Comment by Jonathan-Zollinger** [comment]
I came across the same issue on tumbleweed, thanks to this thread I called `sudo zypper in libX11-devel` which seems to have resolved the issue. Thanks errbody

**Comment by jorgerojas26** [comment]
I'll close this for now. Feel free to reopen if needed.
