### ISSUE TITLE
Suggestion: make the project installable through `homebrew`

### ISSUE THREAD

**Issue by farzadmf** [jorgerojas26/lazysql#5]
Hi,

The project seems really cool, great job!

Wanted to suggest to also support `homebrew` as a way of installing the project (it works both on Mac and Linux)

**Comment by jorgerojas26** [comment]
I want to support as many package managers as i can, but for now my focus is on adding more drivers support and fixing bugs. But after that, i will start working on this.

Anyways, to anyone that wants to contribute, this could be a good addition.

**Comment by pixelskull** [comment]
Looked into this topic. It seems that you have to do this one yourself. To create a tap within homebrew you have to create a seperate repository like this one: https://github.com/neovim/homebrew-neovim

I found this tutorial for creating a `homebrew` tap for a golang cli application, since it also uses goreleaser i thought it may help you. https://askcloudarchitech.com/posts/tutorials/create-homebrew-tap-golang-goreleaser-cobra-cli/

**Comment by farzadmf** [comment]
Yes, it's super easy with `goreleaser` as it does everything automatically (I've done it for one of my own repos).

I could help, but since it needs creating a repo etc., it needs to be done by the owner

**Comment by DanzigerGeist** [comment]
Gentlemen, I have made a formulae which is ready to be merged with the Homebrew core, but it currently lacks a proper test as lazysql does not have any subcommands, like version (ie. `lazysql -v`) to ensure the binary is built properly. Please see here:

https://github.com/DanzigerGeist/homebrew-core/commit/4f0b8b6e5d0e819b50dce6e9250e15f82ddba5e1
 
I am not super-familiar with Go hence I will have to rely on you guys to add this before I can open a pull request with Homebrew. Other than that, the formulae works like a charm, so once as we add any meaningful way to test it on install - we can make it available with brew.

**Comment by ccoVeille** [comment]
thanks

**Comment by farzadmf** [comment]
Just FYI: [goreleaser](https://github.com/goreleaser/goreleaser) provides a very convenient way to publish `brew` packages (haven't tried it with actual `Homebrew` upstream, but was very easy to publish to own custom brew repository)

**Comment by jorgerojas26** [comment]
> Yes, it's super easy with `goreleaser` as it does everything automatically (I've done it for one of my own repos).
> 
> I could help, but since it needs creating a repo etc., it needs to be done by the owner

I'll take a look at this. Thanks.

**Comment by farzadmf** [comment]
Great @jorgerojas26 ; thank you. Small suggestion: you could create a repository called `<user>/homebrew-tap`, where each of the formulas would go there.

With the way it's setup right now, for `lazysql`, you'd have `jorgerojas26/lazysql/lazysql`; then for something else, you'd a new repository `jorgerojas26/<other-tool>`.

But with a central repo, it could be `jorgerojas26/tap/lazysql`, then `jorgerojas26/tap/<other-tool>` (you don't even need to do `jorgerojas26/homebrew-tap/...` and it can be shortened to `jorgerojas26/tap/...`
