### ISSUE TITLE
Bug: program would perminately blocked when operate a empty table 

### ISSUE THREAD

**Issue by LinPr** [jorgerojas26/lazysql#54]
1. what is the problem?
> Bug: program perminately blocked when operate a empty table

2. How to reproduce this problem 
> firstly: enter into a empty table 
> secondly: press up or down key will block the total program forever, and it can not receive keyboard event anymore, even  I press ctrl+c . the program still blocked in somewhere

**Comment by jorgerojas26** [comment]
Fixed in #56
