### ISSUE TITLE
Support for NULL

### ISSUE THREAD

**Issue by pnx** [jorgerojas26/lazysql#57]
Hi, Looks like there is no support for `null`. 

for example:

![image](https://github.com/jorgerojas26/lazysql/assets/398903/df547b61-fdc1-465f-b840-2bdd833e9d45)
![image](https://github.com/jorgerojas26/lazysql/assets/398903/bcdc2ca0-c1fa-460d-9afc-34caab307178)

`email_verified_at` is nullable. and user id 1 has is set to null. there are 2 issues with this:

1. Shows as a empty string in the table. should maybe be shown as "(null)" with even another text color if possible.
2. Unable to set a value to null on either an existing row or when creating a new row. 

attaching a image to show what happens to a datetime when trying to set a empty value. this is maybe fine as an emtpy value is actually not null. it fails correctly i think.

![image](https://github.com/jorgerojas26/lazysql/assets/398903/a2ea95ff-251f-4e3e-a363-752e2c0defd8)

however you can't set it to "null" as it is still a string.

![image](https://github.com/jorgerojas26/lazysql/assets/398903/a0d3c66d-9477-433c-baba-d26d0ea32d97)

I think the cleanest way to solve this is to have a keybind i cell edit mode (maybe Ctrl + N) that will set the column to null. What do you guys think?

**Comment by jorgerojas26** [comment]
This is being worked here #73
