### ISSUE TITLE
PKGBUILD for Archlinux

### ISSUE THREAD

**Issue by OGrigorios** [jorgerojas26/lazysql#6]
Hey, I find great interest in your project, and I hope it will make it as far as lazygit did.

I created a PKGBUILD for this project, so that users of archlinux can install this package.

It's available here: https://aur.archlinux.org/packages/lazysql

Maybe you can update the readme to include it.

Just write something along the lines:

Archlinux users can install it from here: https://aur.archlinux.org/packages/lazysql
via `paru -S lazysql ` or `yay -S lazysql` or by downloading the PKGBUILD file and running `makepkg -si`

**Comment by jorgerojas26** [comment]
Awesome, thank you very much. If you want to make a PR i'll merge it right away, if not, i can make the changes. What you prefer?

**Comment by OGrigorios** [comment]
> Awesome, thank you very much. If you want to make a PR i'll merge it right away, if not, i can make the changes. What you prefer?

PR is read to be merged, feel free to change my formatting or language.
