### ISSUE TITLE
Bug Report: "Relation does not exist" Error in LazySQL

### ISSUE THREAD

**Issue by NoobMasterEz** [jorgerojas26/lazysql#64]
Hello LazySQL Team,

I hope this message finds you well. I am writing to report a bug I encountered while using LazySQL.
While navigating through the tables in my PostgreSQL database, I encountered an error stating that the relation does not exist. The specific error message is:
pq: relation "public.tdymmtaghd" does not exist

**Comment by NoobMasterEz** [comment]
![Screenshot 2567-07-09 at 16 57 51](https://github.com/jorgerojas26/lazysql/assets/25197532/733eb638-02d9-4fb4-a2d7-c1470d29fcc1)

**Comment by jorgerojas26** [comment]
Hi, i think it might be because the name of the table has mixed-case spelling. I'll take a look at this.

**Comment by jorgerojas26** [comment]
@NoobMasterEz  Can you check if #65 solves your problem?

**Comment by NoobMasterEz** [comment]
@jorgerojas26 it works thank
