### ISSUE TITLE
Improve code quality by using golangci-lint

### ISSUE THREAD

**Issue by ccoVeille** [jorgerojas26/lazysql#71]
We could set up golangci-lint rules in the repository that could be checked with a GitHub action.

It would help to keep code quality

**Comment by ccoVeille** [comment]
I'm opening the issue, but I'm also available to help on this, as it's something I know well

**Comment by jorgerojas26** [comment]
That would be awesome. I'm not very familiar with golangci-lint so, your help will be very appreciated. Thanks.

**Comment by ccoVeille** [comment]
For status and records, here is the current status of lazygit with current code

```
226 issues:
* errcheck: 26
* gci: 29
* gosec: 15
* rowserrcheck: 24
* sqlclosecheck: 6
* revive: 126
```

Here is the detail for revive

```
     26 revive.unhandled-error
     22 revive.bare-return
     19 revive.use-any
     16 revive.max-control-nesting
      6 revive.redefines-builtin-id
      5 revive.var-declaration
      5 revive.indent-error-flow
      4 revive.var-naming
      4 revive.unexported-naming
      3 revive.unused-receiver
      3 revive.unnecessary-stmt
      3 revive.unchecked-type-assertion
      3 revive.blank-imports
      2 revive.unused-parameter
      2 revive.dot-imports
      1 revive.identical-branches
      1 revive.early-return
      1 revive.confusing-results
```

Some might be opinionated, I'm using almost all possible linter available.

I don't think all of them need to be activated for your project.
