### ISSUE TITLE
Parse password with special characters

### ISSUE THREAD

**Issue by Rahmerh** [jorgerojas26/lazysql#74]
When using the following configuration snippet:
```
[[database]]
Name = 'localhost'
Provider = 'postgres'
DBName = 'default'
URL = 'pg://postgres:t9>EBKfHKmp0!@localhost:2001/default'
```
(Password is not the real one of course)

I get the following error:
![image](https://github.com/user-attachments/assets/f9be81a3-9a4b-4457-8e24-442410751449)

It works just fine if I have a password without special characters. I've tried escaping special characters but no luck so far. Is this something I'm doing wrong on my end or is it not yet possible in the tool?

_I appreciate the work you put in regardless! I've been using this tool and it makes it so much easier to work with my databases, thanks!_

**Comment by jorgerojas26** [comment]
Hi,

if you password has special characters, you must URL encode it. So, if you password is:

t9>EBKfHKmp0!

you must URL encode like this:

t9%3EEBKfHKmp0%21

**Comment by Rahmerh** [comment]
Ah great, would it possible to at least include this in the documentation?

**Comment by jorgerojas26** [comment]
Yes, of course. I will be adding it shortly.

Thank you, I'll close this.
