### ISSUE TITLE
I've been unable to connect mysql databse

### ISSUE THREAD

**Issue by AB10110F** [jorgerojas26/lazysql#77]
I'm trying to follow the placeholder provided on the readme, but the @ is not displaying and shows the following error

![image](https://github.com/user-attachments/assets/2423ee89-83ba-441d-93bf-59fe32a74f0b)

Thanks beforehand

**Comment by jorgerojas26** [comment]
Without the @ is not going to work. That may be an issue with your keyboard or something like that, i cannot reproduce the problem.

**Comment by AB10110F** [comment]
@jorgerojas26 If I copy the url from lazysql and paste it somewhere else the @ appears, but I have no idea of why it is not working inside lazysql. I installed it with go to run it on windows btw.

**Comment by jorgerojas26** [comment]
> @jorgerojas26 If I copy the url from lazysql and paste it somewhere else the @ appears, but I have no idea why it is not working inside lazysql. I installed it with go to run it on windows btw.

It can be a problem with copy/paste in your terminal. Check if the same problem occurs in other terminal programs.

**Comment by oskretc** [comment]
does you password contains # symbol, I think there is an issue when a # symbol is used anywhere in the connection string

**Comment by jorgerojas26** [comment]
> does you password contains # symbol, I think there is an issue when a # symbol is used anywhere in the connection string

If the password contains special characters, it must be url encoded.

**Comment by jorgerojas26** [comment]
I'm closing this for now. If the problem persist, feel free to reopen.
