### ISSUE TITLE
Fix possible SQL Injection

### ISSUE THREAD

**Issue by ccoVeille** [jorgerojas26/lazysql#79]
> > May i ask why SQL Injection is a concern to you in this app when it is just a SQL client?
> 
> My SQL injection I was more thinking about a source of bugs, than a attack.
> 
> Maybe it's what you were asking for

I understand. I appreciate the feedback. For now, i'll merge this PR just to resolve the connection problem and open another PR addressing your feedback.

Thank you very much.

_Originally posted by @jorgerojas26 in https://github.com/jorgerojas26/lazysql/pull/67#issuecomment-2220807680_

**Comment by jorgerojas26** [comment]
Addressed in #73
