### ISSUE TITLE
[feat]: SQlite

### ISSUE THREAD

**Issue by dhruvinsh** [jorgerojas26/lazysql#8]
Good cli app concept. 

SQlite support would be good as well as future development.

**Comment by MaxThom** [comment]
+1, ive been trying to find a good TUI for SQL and no success. Your lazysql look stunning already.
I'm using sqlite3 and postgres

**Comment by GusJelly** [comment]
I'm willing to work on the sqlite stuff, I would like to ask what would be needed to do to add support. I am reading the code right now and I can see that would need to add an sqlite.go file with code that supports the driver. Is there anything else that would need to be done besides that?

**Comment by MaxThom** [comment]
Likewise, I could try the Postgres implementation!

**Comment by jorgerojas26** [comment]
I am working on the code refactor to support multiple drivers, it should be ready today, maybe tomorrow. With those changes, supporting more drivers will be easy. I'll let you know when it's ready so we all can start adding drivers.

**Comment by jaymorelli96** [comment]
Cool!! I am very excited about this project, great work @jorgerojas26. I would also be happy to help with implementation or documentation 😄

**Comment by GusJelly** [comment]
Thank you for your work @jorgerojas26. Excited for this amazing software, I'll sync my fork and start work on the sqlite driver.

**Comment by jorgerojas26** [comment]
> I am working on the code refactor to support multiple drivers, it should be ready today, maybe tomorrow. With those changes, supporting more drivers will be easy. I'll let you know when it's ready so we all can start adding drivers.

I just merged a PR with these changes and added Postgres support. Next will be SQLite. 

@GusJelly Do you want to work on the SQLite implementation?

**Comment by GusJelly** [comment]
> > I am working on the code refactor to support multiple drivers, it should be ready today, maybe tomorrow. With those changes, supporting more drivers will be easy. I'll let you know when it's ready so we all can start adding drivers.
> 
> I just merged a PR with these changes and added Postgres support. Next will be SQLite.
> 
> @GusJelly Do you want to work on the SQLite implementation?

Going to sync to start working on it now. Going to read the refactor to see what I need to do.

**Comment by GusJelly** [comment]
I running into issues when trying to create an SQLite connection. My code is on a separate SQLite branch on my personal fork.

## The problem
Even if I use an absolute path like `sqlite3:/path/to/file` in the connection input. I get a segmentation fault. The error message tells me it's on: "lazysql/components/ConnectionSelection.go" on line 156.

I apologize but I am new to this type of program in go so any help would be appreciated.
