### ISSUE TITLE
macos: brew install cannot connect to sqlite databases

### ISSUE THREAD

**Issue by bdmorin** [jorgerojas26/lazysql#84]
I installed lazysql fresh from homebrew.
I added a connection to a file, and get the message:
```
Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
```

Pretty sure I know how to fix this, but I wanted to report it.

**Comment by jorgerojas26** [comment]
Amazing, feel free to open a PR.
