### ISSUE TITLE
Don't trigger backspace global keybind when in text fields

### ISSUE THREAD

**Issue by AndreVolpi** [jorgerojas26/lazysql#85]
Hello, when I am querying tables, sometimes I make typos and my immediate response is to use backspace, but then it moves me to connection screen, would be nice if in editor fields backspace worked like a backspace.

**Comment by jorgerojas26** [comment]
Backspace should work properly when you are in an input, like the "WHERE" input and the SQL Editor. I cannot reproduce the problem.

**Comment by joelpaulkoch** [comment]
Hi, thanks for creating lazysql, this looks cool and fun. I have the same problem. I'm on MacOS and lazysql version 0.2.4

**Comment by joelpaulkoch** [comment]
I can actually reproduce the problem on my linux machine (which says version "dev", but that should be version 0.2.4 as well, from nixpkgs unstable), it occurs when following these steps:
1. open a connection, go into the sql editor (ctrl+e), now if I type something and press backspace everything is still fine
2. leave the sql editor (I press ESC)
3. go back into the sql editor (I click inside)
4. the previous text is still there, if I press backspace I'm back to the connection screen

**Comment by sktzofrenic** [comment]
I have the same problem with the backspace key.

**Comment by hrvstr** [comment]
> I'm experiencing this too (MacOS Sonoma), found a temporary fix for this is using `ctrl+backspace` instead of just `backspace`

Workaround does not seem to work for me on Sonoma using Alacritty. No way to remove text from the input field.
