### ISSUE TITLE
Can't edit data in postgresql

### ISSUE THREAD

**Issue by irdaislakhuafa** [jorgerojas26/lazysql#87]
[url](https://github.com/user-attachments/assets/932b63f9-9a33-4cfe-b865-c721c985d512)

I can't change the data in postgresql, the error message shows `pq: zero-length delimited identifier at or near " " " "` but it works fine in mysql, is there any solution?

**Comment by jorgerojas26** [comment]
Hi, the video url is not working.

**Comment by irdaislakhuafa** [comment]
> Hi, the video url is not working.

thank you, i have changed the video url, now you can see it

**Comment by jorgerojas26** [comment]
It's still not viewable.

**Comment by irdaislakhuafa** [comment]
> It's still not viewable.

please try open github issue on browser, i use chrome here and i can see it
![image](https://github.com/user-attachments/assets/c6627883-b3b5-44ee-834e-9d8c4f67707c)

**Comment by jorgerojas26** [comment]
I'm looking to resolve this.

**Comment by PravithBA** [comment]
I was also facing this issue, it was adding quotes for the table name twice, i removed the adding of quotes to the table name in drivers/postgres.go:617 and it worked for me

**Comment by PravithBA** [comment]
I was also facing this issue, it was adding quotes for the table name twice, i removed the adding of quotes to the table name in drivers/postgres.go:617 and it worked for me. @jorgerojas26

**Comment by jorgerojas26** [comment]
I'm working on a DML statements refactor in #73

**Comment by jorgerojas26** [comment]
Can you guys check if #73 solves this problem?

**Comment by irdaislakhuafa** [comment]
> Can you guys check if #73 solves this problem?

thanks bro, issue is fixed!
